"""
If you finish this kata, you can try Insane Coloured Triangles by Bubbler,
 which is a much harder version of this one.

A coloured triangle is created from a row of colours, each of which is red,
green or blue. Successive rows, each containing one fewer colour than the last,
are generated by considering the two touching colours in the previous row.
If these colours are identical, the same colour is used in the new row.
If they are different, the missing colour is used in the new row.
This is continued until the final row, with only a single colour, is generated.
The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G

"""
import codewars_test as test
def triangle(row):
    COLORS = set('RGB')
    while len(row)>1:
        row = ''.join(a if a==b else (COLORS - {a,b}).pop() for a,b in zip(row, row[1:]))
    return row
def gen(c1,c2):
    if c1!=c2:
        for c in ['R','G','B']:
            if c1 != c and c2 != c:
                return c
    else:
        return c1

@test.describe("Fixed Tests")
def fixed_tests():
    @test.it('Basic Test Cases')
    def basic_test_cases():
        test.assert_equals(triangle('GB'), 'R')
        test.assert_equals(triangle('RRR'), 'R')
        test.assert_equals(triangle('RGBG'), 'B')
        test.assert_equals(triangle('RBRGBRB'), 'G')
        test.assert_equals(triangle('RBRGBRBGGRRRBGBBBGG'), 'G')
        test.assert_equals(triangle('B'), 'B')